version: "3.8"

services:
    mysql:
        image: mysql:latest
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # ✅ Cho phép root không cần mật khẩu
            MYSQL_DATABASE: customer_be
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - ecommerce_network

    mongodb:
        image: mongo:latest
        container_name: mongo_db
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
        networks:
            - ecommerce_network

    customer_service:
        build: ./customer
        container_name: customer_service
        restart: always
        depends_on:
            - mysql
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_NAME: customer_be
            DB_USER: root
            DB_PASSWORD: ""
        ports:
            - "8005:8005"
        networks:
            - ecommerce_network

    order_service:
        build: ./order_service
        container_name: order_service
        restart: always
        environment:
            DB_ENGINE: django.db.backends.sqlite3
            DB_NAME: /db.sqlite3
        volumes:
            - order_data:/app/data
        ports:
            - "8006:8006"
        networks:
            - ecommerce_network

    cart_service:
        build: ./cart_service
        container_name: cart_service
        restart: always
        environment:
            DB_ENGINE: django.db.backends.sqlite3
            DB_NAME: /db.sqlite3
        volumes:
            - cart_data:/app/data
        ports:
            - "8003:8003"
        networks:
            - ecommerce_network

    payment_service:
        build: ./payment_service
        container_name: payment_service
        restart: always
        environment:
            DB_ENGINE: django.db.backends.sqlite3
            DB_NAME: /db.sqlite3
        volumes:
            - payment_data:/app/data
        ports:
            - "8007:8007"
        networks:
            - ecommerce_network

    book_service:
        build: ./book_service
        container_name: book_service
        restart: always
        depends_on:
            - mongodb
        environment:
            MONGO_URI: mongodb+srv://FirstDemo:gRiFtXz20PlbtrwK@cluster0.nnzr3gd.mongodb.net/ecommerce_book
        ports:
            - "8002:8002"
        networks:
            - ecommerce_network

    phone_service:
        build: ./phone_service
        container_name: phone_service
        restart: always
        depends_on:
            - mongodb
        environment:
            MONGO_URI: mongodb+srv://FirstDemo:gRiFtXz20PlbtrwK@cluster0.nnzr3gd.mongodb.net/ecommerce_phone
        ports:
            - "8008:8008"
        networks:
            - ecommerce_network

    clothes_service:
        build: ./clothes_service
        container_name: clothes_service
        restart: always
        depends_on:
            - mongodb
        environment:
            MONGO_URI: mongodb+srv://FirstDemo:gRiFtXz20PlbtrwK@cluster0.nnzr3gd.mongodb.net/ecommerce_clothes
        ports:
            - "8004:8004"
        networks:
            - ecommerce_network

volumes:
    mysql_data:
    mongo_data:
    order_data:
    cart_data:
    payment_data:

networks:
    ecommerce_network:
        driver: bridge
